import { Router } from 'express';
import authRoutes from './auth.routes.js';
import employeeRoutes from './employee.routes.js';
import departmentRoutes from './department.routes.js';
import attendanceRoutes from './attendance.routes.js';
import leaveRoutes from './leave.routes.js';
import payrollRoutes from './payroll.routes.js';
import performanceRoutes from './performance.routes.js';
import performanceManagementRoutes from './performance-management.routes.js';
import recruitmentRoutes from './recruitment.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import assetRoutes from './asset.routes.js';
import documentRoutes from './document.routes.js';
import notificationRoutes from './notification.routes.js';
import trainingRoutes from './training.routes.js';
import reportRoutes from './report.routes.js';
import reportsRoutes from './reports.routes.js';
import helpdeskRoutes from './helpdesk.routes.js';
import holidayRoutes from './holiday.routes.js';
import roleRoutes from './role.routes.js';
import onboardingRoutes from './onboarding.routes.js';
import settingsRoutes from './settings.routes.js';
import auditRoutes from './audit.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/employees', employeeRoutes);
router.use('/departments', departmentRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/leaves', leaveRoutes);
router.use('/payroll', payrollRoutes);
router.use('/performance', performanceRoutes);
router.use('/performance-management', performanceManagementRoutes);
router.use('/recruitment', recruitmentRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/assets', assetRoutes);
router.use('/documents', documentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/trainings', trainingRoutes);
router.use('/reports', reportRoutes);
router.use('/reports-v2', reportsRoutes);
router.use('/helpdesk', helpdeskRoutes);
router.use('/holidays', holidayRoutes);
router.use('/roles', roleRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/settings', settingsRoutes);
router.use('/audit', auditRoutes);

export default router;
